# alacritty toml
live_config_reload = true

[shell]
program = "/bin/fish"

[window]
padding = { x = 4, y = 4 }
dynamic_padding = true
decorations = "Full"
opacity = 0.92
blur = true
startup_mode = "Windowed"
title = "blackbeard os"
dynamic_title = true

[scrolling]
history = 5000

[font]
size = 9
normal.family = "Hurmit Nerd Font"
bold.family = "Hurmit Nerd Font"
italic.family = "Hurmit Nerd Font"

# Colors (Everforest Dark)
## Default colors
[colors.primary]
background = '#2d353b'
foreground = '#d3c6aa'

## Normal colors
[colors.normal]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

## Bright colors
[colors.bright]
black   = '#475258'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[mouse]
hide_when_typing = true
